title: Ryan Thomas # your name (or website title) here
logo: "/images/Thomas_Ryan.jpg?raw=True" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)  
  <br>
  <br><br>
  <a href="https://www.linkedin.com/in/ryan-thomas-092b00200/">LinkedIn</a> 
  <br>
  <a href="/images/Resume_RyanThomas_2023.pdf" class="btn btn--info">Resume</a>  
  <br>
  <a href="https://github.com/ryant382">GitHub</a>  
  <br>
  
theme: jekyll-theme-minimal
